- core/src/main/scala/codesearch/core/index/HaskellIndex.scala
- core/src/main/scala/codesearch/core/index/JavaScriptIndex.scala
- core/src/main/scala/codesearch/core/index/LanguageIndex.scala
- core/src/main/scala/codesearch/core/index/RubyIndex.scala
- core/src/main/scala/codesearch/core/index/RustIndex.scala
- core/src/main/scala/codesearch/core/util/Helper.scala
- web-server/app/codesearch/web/controllers/CratesSearcher.scala
- web-server/app/codesearch/web/controllers/GemSearcher.scala
- web-server/app/codesearch/web/controllers/HackageSearcher.scala
- web-server/app/codesearch/web/controllers/NpmSearcher.scala
- web-server/app/views/javascript_search.scala.html
- web-server/app/views/resultFrame.scala.html
- web-server/app/views/ruby_search.scala.html
- web-server/app/views/rust_search.scala.html
- web-server/app/views/search.scala.html
> Issue #71 (code cleanup): step 3: define case classes

- project/Builder.scala
- project/plugins.sbt
- web-server/conf/routes
> [#70] Setup fingerprint for assets

- project/Builder.scala
https://github.com/aelve/codesearch/issues/103
> [#103] - Deduplicate: different file contents found in the following

- core/src/main/resources/application.conf
- core/src/main/scala/codesearch/core/config/Config.scala
- core/src/main/scala/codesearch/core/index/LanguageIndex.scala
- core/src/main/scala/codesearch/core/search/Searcher.scala
- core/src/main/scala/codesearch/core/util/Helper.scala
- core/src/test/scala/ConfigSpec.scala
- web-server/app/codesearch/web/controllers/SearchController.scala
> [#112] Change page defaults to something more reasonable

- core/src/main/scala/codesearch/core/index/LanguageIndex.scala
- core/src/main/scala/codesearch/core/search/Searcher.scala
- core/src/main/scala/codesearch/core/util/Helper.scala
- web-server/app/codesearch/web/controllers/SearchController.scala
> [#108] Leaked file descriptors

- .dockerignore
- .gitignore
- Makefile
- core/src/main/resources/application.conf
- core/src/main/scala/codesearch/core/index/RustIndex.scala
- docker/README.MD
- docker/core/Dockerfile
- docker/core/Makefile
- docker/web-server/Dockerfile
It's better to review commit-by-commit.
> Various Docker-related fixes

- Makefile
- docker/README.MD
- docker/core/Dockerfile
- docker/web-server/Dockerfile
- docker/web-server/Makefile
* Add make commands for pushing images.
* Slightly rewrite the Docker readme again.
* Use `apk --no-cache` uniformly.
* Reorder Dockerfile layers to make caching slightly nicer.
* Add a makefile for the web-server Docker image to work around some weird
Java+Alpine bug (https://github.com/docker-library/openjdk/issues/77)
> More more Docker-related improvements

- core/src/main/scala/codesearch/core/regex/lexer/Tokenizer.scala
- core/src/main/scala/codesearch/core/regex/lexer/tokens/Token.scala
- core/src/main/scala/codesearch/core/regex/space/SpaceInsensitive.scala
- core/src/main/scala/codesearch/core/search/Search.scala
- core/src/test/scala/codesearch/core/regex/lexer/TokenizerSpec.scala
- core/src/test/scala/codesearch/core/regex/space/SpaceInsensitiveSpec.scala
> [#150] Charset classes

- core/src/main/scala/codesearch/core/regex/lexer/Tokenizer.scala
- core/src/main/scala/codesearch/core/regex/lexer/tokens/Token.scala
- core/src/main/scala/codesearch/core/regex/space/SpaceInsensitive.scala
- core/src/test/scala/codesearch/core/regex/lexer/TokenizerSpec.scala
- core/src/test/scala/codesearch/core/regex/space/SpaceInsensitiveSpec.scala
> [#159] Refactoring test and added new case in "space insensitive processing"

- core/src/main/scala/codesearch/core/regex/lexer/Tokenizer.scala
- core/src/main/scala/codesearch/core/regex/lexer/tokens/Token.scala
- core/src/main/scala/codesearch/core/regex/space/SpaceInsensitive.scala
- core/src/test/scala/codesearch/core/regex/lexer/TokenizerSpec.scala
- core/src/test/scala/codesearch/core/regex/space/SpaceInsensitiveSpec.scala
> [#160] posix classes test

- core/src/main/scala/codesearch/core/db/DefaultDB.scala
- core/src/main/scala/codesearch/core/search/Search.scala
https://github.com/aelve/codesearch/issues/185
> [#185] Fixed hackage links on preview pages

- .gitignore
- core/src/main/scala/codesearch/core/search/Search.scala
- core/src/main/scala/codesearch/core/search/SnippetsGrouper.scala
- core/src/test/scala/codesearch/core/search/SnippetsGrouperSpec.scala
- web-server/app/codesearch/web/SnippetHelper.scala
- web-server/app/views/resultFrame.scala.html
> [#67] Group code snippets

- Makefile
- README.md
- docker/core/Makefile
- docker/web-server/Makefile
* Makefile commands inside docker and outside docker now have same names
* The README has been updated to mention @Evengining's fork
* "make serve" works out of the box now
> [#noissue] Minor fixes

- core/src/main/scala/codesearch/core/search/Search.scala
- core/src/main/scala/codesearch/core/search/SearchRequest.scala
- web-server/app/codesearch/web/controllers/SearchController.scala
- web-server/app/views/search.scala.html
- web-server/app/views/searchBox.scala.html
- web-server/app/views/search_results.scala.html
- web-server/conf/routes
- web-server/public/css/search.css
Now the filter field is checked for emptiness. The request field will also be checked (in the future, if all goes well). I also refactor csearch, there is also a check, filter and query.
> [#noissue] Fixed bug with fields validation

- core/src/main/scala/codesearch/core/db/DefaultDB.scala
- core/src/main/scala/codesearch/core/index/LanguageIndex.scala
- core/src/main/scala/codesearch/core/index/RustIndex.scala
- core/src/main/scala/codesearch/core/index/details/NpmDetails.scala
- core/src/main/scala/codesearch/core/index/directory/CSearchDirectory.scala
- core/src/main/scala/codesearch/core/index/directory/Directory.scala
- core/src/main/scala/codesearch/core/syntax/path.scala
- core/src/main/scala/codesearch/core/syntax/stream.scala
- core/src/main/scala/codesearch/core/util/fs2/stream.scala
- project/build.properties
Related to: https://github.com/aelve/codesearch/issues/194
> [#noissue] Temporary fix memory overhead when checking existsing packages from the db

- core/src/main/scala/codesearch/core/index/repository/FileFilter.scala
- core/src/main/scala/codesearch/core/index/repository/SourcePackage.scala
https://github.com/aelve/codesearch/issues/201
> Fixed error while extracting Gems archives

- web-server/app/views/searchBox.scala.html
- web-server/public/css/search.css
> [#203] Added warning about entering more than two characters.

- web-server/app/views/docFrame.scala.html
- web-server/app/views/searchBox.scala.html
- web-server/public/css/common.css
- web-server/public/css/search.css
Fixes #208.
This PR also changes field order in the search form and messes with styles a bit, see attached screenshot.
> [#208] Add a manual

- core/src/main/scala/codesearch/core/CLI.scala
- core/src/main/scala/codesearch/core/Main.scala
- core/src/main/scala/codesearch/core/Program.scala
- core/src/main/scala/codesearch/core/index/LanguageIndex.scala
> [#211] Download a limited count of packages

- web-server/app/views/wrapper.scala.html
- web-server/public/css/common.css
> [#212] Rewrite the footer

- README.md
- core/src/main/resources/application.conf
- core/src/main/resources/production.conf
- core/src/main/scala/codesearch/core/config/Config.scala
- web-server/app/codesearch/web/MamotoMetrics.scala
- web-server/app/views/searchResults.scala.html
- web-server/app/views/sourceCode.scala.html
- web-server/app/views/wrapper.scala.html
> [#219] Remove Content-Security-Policy

- web-server/app/codesearch/web/SnippetHelper.scala
Issue: https://github.com/aelve/codesearch/issues/221
> [#221] Fixed incorrect rendering of source file view page

- web-server/app/views/searchBox.scala.html
Also need to update csearch on the server.
> [#217] Removed restriction

- core/src/main/scala/codesearch/core/regex/RegexConstructor.scala
- core/src/main/scala/codesearch/core/search/Search.scala
- core/src/test/scala/codesearch/core/regex/PreciseMatchSpec.scala
- web-server/app/views/resultFrame.scala.html
> [#236] flag removed in csearch arguments

- core/src/main/scala/codesearch/core/config/Config.scala
- core/src/main/scala/codesearch/core/search/Search.scala
- web-server/app/codesearch/web/controllers/SearchController.scala
- web-server/app/views/pagination.scala.html
- web-server/app/views/searchResults.scala.html
Issue: https://github.com/aelve/codesearch/issues/242
> [#242] Fixed display of the total number of matches on the search results page

- core/src/main/scala/codesearch/core/index/repository/SourcePackage.scala
- core/src/main/scala/codesearch/core/search/SearchRequest.scala
- web-server/app/codesearch/web/controllers/SearchController.scala
- web-server/app/views/searchBox.scala.html
Issue: https://github.com/aelve/codesearch/issues/240
> [#240] Filtering non-printable characters from request parameters

- README.md
> [#noissue] Add tests badge
